import Head from "next/head"
import Image from "next/image"
import { Inter } from "next/font/google" 
import { useState } from "react" 
import axios from "axios"
const inter = Inter({ subsets: ["latin"] })



export default function Home() {
    const [selectedItem, setSelectedItem] = useState("");
    const [options, setOptions] = useState([]);
    const [formData, setFormData] = useState({});
    const handleChange = (event) => {
        setFormData({ ...formData, [event.target.name]: event.target.value });
       
      };
      const handleSubmit = (event) => {
        event.preventDefault();
        axios.post('https://sheet.best/api/sheets/049e7c3e-18a0-4ff3-b540-494bd3d20598' , formData).then((res) => {
            console.log(res)
        })
      };
    const [languageSelected, setlanguageSelected] = useState(false)
    const handleFirstDropdownChange = (event) => {
        setFormData({ ...formData, [event.target.name]: event.target.value });
      const selected = event.target.value;
      setSelectedItem(selected);
  
      // Update options for the second dropdown list based on the selected item
      if (selected === "Langue") {
        setOptions(["Allemand", "Anglais", "Français"]);
      } else if (selected === "IT") {
        setOptions(["Power BI & Preparation à la certification PL-300 ", "E-commerce Tunisie", "Graphic Design Illustrator"]);
      }  
      setSelectedItem(selected === "Langue")
      console.log(selectedItem)
    };
 
  return (
    <>
      <Head>
        <title> Préinscription FBS </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>  
<section class="bg-white  :bg-gray-900 bg-from">
<div id="successModal" tabindex="-1" aria-hidden="true" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-modal md:h-full">
    <div class="relative p-4 w-full max-w-md h-full md:h-auto">
 
        <div class="relative p-4 text-center bg-white rounded-lg shadow dark:bg-gray-800 sm:p-5">
            <button type="button" class="text-gray-400 absolute top-2.5 right-2.5 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white" data-modal-toggle="successModal">
                <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                <span class="sr-only">Close modal</span>
            </button>
            <div class="w-12 h-12 rounded-full bg-green-100 dark:bg-green-900 p-2 flex items-center justify-center mx-auto mb-3.5">
                <svg aria-hidden="true" class="w-8 h-8 text-green-500 dark:text-green-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                <span class="sr-only">Success</span>
            </div>
            <p class="mb-4 text-lg font-semibold text-gray-900 dark:text-white">Successfully removed product.</p>
            <button data-modal-toggle="successModal" type="button" class="py-2 px-3 text-sm font-medium text-center text-white rounded-lg bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 dark:focus:ring-primary-900">
                Continue
            </button>
        </div>
    </div>
</div>
    <div class="flex justify-center min-h-screen  " >
        <div class="hidden bg-cover lg:block lg:w-1/2" style={{
  backgroundImage: "url('/background.jpg')",
  zIndex:233
  // Add any other styles you want to apply to the div here
}}>
        </div>

        <div class="flex items-center w-full max-w-3xl p-8 mx-auto lg:px-12 lg:w-3/5 bg-form">
           
           
            <div class="w-full  ">
           
            <Image loading="lazy" src={'/iconFBS.png'} width={400} height={400}  className="mx-auto fade-in-image"  />
                <h1 class="text-2xl font-semibold tracking-wider text-gray-800   :text-white">
                    Inscrivez vous chez FBS 
                </h1>

                <p class="mt-4 text-gray-500  :text-gray-400">
                Faites votre préinscription maintenant 
                      </p>

              

                <form class="grid grid-cols-1 gap-6 mt-8 md:grid-cols-1" onSubmit={handleSubmit} method="post">
                    <div>
                        <label class="block mb-2 text-sm text-gray-600  :text-gray-200">Nom</label>
                        <input  onChange={handleChange} name="nom" type="text" placeholder="Nom" class="block w-full px-5 py-3 mt-2 text-gray-700 placeholder-gray-400 bg-white border border-gray-200 rounded-md  :placeholder-gray-600  :bg-gray-900  :text-gray-500  :border-gray-700 focus:border-blue-400  :focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40" />
                    </div>

                    <div>
                        <label class="block mb-2 text-sm text-gray-600  :text-gray-200">Prénom</label>
                        <input type="text"  onChange={handleChange} name="prenom" placeholder="Prénom" class="block w-full px-5 py-3 mt-2 text-gray-700 placeholder-gray-400 bg-white border border-gray-200 rounded-md  :placeholder-gray-600  :bg-gray-900  :text-gray-500  :border-gray-700 focus:border-blue-400  :focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40" />
                    </div>

                    <div>
                        <label class="block mb-2 text-sm text-gray-600  :text-gray-200">Numéro de téléphone</label>
                        <input type={"number"}  onChange={handleChange} name="tel" maxLength={8} placeholder="+216 XX XXX XXX " class="block w-full px-5 py-3 mt-2 text-gray-700 placeholder-gray-400 bg-white border border-gray-200 rounded-md  :placeholder-gray-600  :bg-gray-900  :text-gray-500  :border-gray-700 focus:border-blue-400  :focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40" />
                    </div>

                    <div>
                        <label class="block mb-2 text-sm text-gray-600  :text-gray-200">Adresse Email</label>
                        <input type="email"  onChange={handleChange} name="email" placeholder="nomprenom@example.com" class="block w-full px-5 py-3 mt-2 text-gray-700 placeholder-gray-400 bg-white border border-gray-200 rounded-md   :text-gray-500  :border-gray-700 focus:border-blue-400  :focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40" />
                    </div>

    
<label for="underline_select" class="sr-only">Choisir formation</label>
  
                       
<select  onChange={handleFirstDropdownChange}   name="Type"  className="block py-2.5 px-0 w-full text-sm text-gray-500 bg-transparent border-0 border-b-2 border-gray-200 appearance-none  :text-gray-400  :border-gray-700 focus:outline-none focus:ring-0 focus:border-gray-200 peer"  id="first-dropdown" >
        <option value="" selected disabled >Type de formation</option>
        <option value="Langue">Formation lingustique</option>
        <option  value="IT">Formation IT</option> 
      </select>

      <select id="second-dropdown" onChange={handleChange} name="formation" className="block py-2.5 px-0 w-full text-sm text-gray-500 bg-transparent border-0 border-b-2 border-gray-200 appearance-none  :text-gray-400  :border-gray-700 focus:outline-none focus:ring-0 focus:border-gray-200 peer" >
      <option value="" selected disabled >Choisir formation</option>
        {options.map((option) => (
          <option key={option} value={option}>
            {option}
          </option>
        ))}
      </select>
    
      
                     
 
    {
        selectedItem && 
        <div>
            <label class="block text-sm text-gray-600  :text-gray-200 mb-4">Niveau Langue :</label>
            <ul class="w-90 text-sm font-medium text-gray-500 bg-white border border-gray-200 rounded-lg dark:bg-white-700 dark:border-gray-600 dark:text-white">
           
            <li class="w-full border-b border-gray-200 rounded-t-lg dark:border-gray-600">
                <div class="flex items-center pl-3">
                    <input id="list-radio-license" type="radio" value="A1"  onChange={handleChange} name="niveau" class="" />
                    <label for="list-radio-license" class="w-full py-3 ml-2 text-sm font-medium text-gray-500 dark:text-gray-500">Niveau A1 </label>
                </div>
            </li>
            <li class="w-full border-b border-gray-200 rounded-t-lg dark:border-gray-600">
                <div class="flex items-center pl-3">
                    <input id="list-radio-id" type="radio" value="A2"  onChange={handleChange} name="niveau" class="dark:ring-offset-white-700 dark:focus:focus:ring-2 dark: dark:border-gray-500" />
                    <label for="list-radio-id" class="w-full py-3 ml-2 text-sm font-medium text-gray-500 dark:text-gray-500">Niveau A2</label>
                </div>
            </li>
            <li class="w-full border-b border-gray-200 rounded-t-lg dark:border-gray-600">
                <div class="flex items-center pl-3">
                    <input id="list-radio-millitary" type="radio" value="B1"  onChange={handleChange} name="niveau" class="" />
                    <label for="list-radio-millitary" class="w-full py-3 ml-2 text-sm font-medium text-gray-500 dark:text-gray-500">Niveau B1</label>
                </div>
            </li>
            <li class="w-full border-b border-gray-200 rounded-t-lg dark:border-gray-600">
                <div class="flex items-center pl-3">
                    <input id="list-radio-passport" type="radio" value="B2"  onChange={handleChange} name="niveau" class="" />
                    <label for="list-radio-passport" class="w-full py-3 ml-2 text-sm font-medium text-gray-500 dark:text-gray-500">Niveau B2</label>
                </div>
            </li>
        </ul>
        </div>
   
    }

 
<button
  type="button"
  class="inline-block rounded bg-primary px-6 pt-2.5 pb-2 text-xs font-medium uppercase leading-normal text-white shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-primary-600 hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:bg-primary-600 focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:outline-none focus:ring-0 active:bg-primary-700 active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]"
  data-te-toggle="modal"
  data-te-target="#staticBackdrop"
  data-te-ripple-init
  data-te-ripple-color="light">
  Launch static backdrop modal
</button>
 
<div
  data-te-modal-init
  class="fixed top-0 left-0 z-[1055] hidden h-full w-full overflow-y-auto overflow-x-hidden outline-none"
  id="staticBackdrop"
  data-te-backdrop="static"
  data-te-keyboard="false"
  tabindex="-1"
  aria-labelledby="staticBackdropLabel"
  aria-hidden="true">
  <div
    data-te-modal-dialog-ref
    class="pointer-events-none relative w-auto translate-y-[-50px] opacity-0 transition-all duration-300 ease-in-out min-[576px]:mx-auto min-[576px]:mt-7 min-[576px]:max-w-[500px]">
    <div
      class="min-[576px]:shadow-[0_0.5rem_1rem_rgba(#000, 0.15)] pointer-events-auto relative flex w-full flex-col rounded-md border-none bg-white bg-clip-padding text-current shadow-lg outline-none dark:bg-neutral-600">
      <div
        class="flex flex-shrink-0 items-center justify-between rounded-t-md border-b-2 border-neutral-100 border-opacity-100 p-4 dark:border-opacity-50">
        <h5
          class="text-xl font-medium leading-normal text-neutral-800 dark:text-neutral-200"
          id="exampleModalLabel">
          Modal title
        </h5>
        <button
          type="button"
          class="box-content rounded-none border-none hover:no-underline hover:opacity-75 focus:opacity-100 focus:shadow-none focus:outline-none"
          data-te-modal-dismiss
          aria-label="Close">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            class="h-6 w-6">
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div data-te-modal-body-ref class="relative p-4">...</div>
      <div
        class="flex flex-shrink-0 flex-wrap items-center justify-end rounded-b-md border-t-2 border-neutral-100 border-opacity-100 p-4 dark:border-opacity-50">
        <button
          type="button"
          class="inline-block rounded bg-primary-100 px-6 pt-2.5 pb-2 text-xs font-medium uppercase leading-normal text-primary-700 transition duration-150 ease-in-out hover:bg-primary-accent-100 focus:bg-primary-accent-100 focus:outline-none focus:ring-0 active:bg-primary-accent-200"
          data-te-modal-dismiss
          data-te-ripple-init
          data-te-ripple-color="light">
          Close
        </button>
        <button
          type="button"
          class="ml-1 inline-block rounded bg-primary px-6 pt-2.5 pb-2 text-xs font-medium uppercase leading-normal text-white shadow-[0_4px_9px_-4px_#3b71ca] transition duration-150 ease-in-out hover:bg-primary-600 hover:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:bg-primary-600 focus:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)] focus:outline-none focus:ring-0 active:bg-primary-700 active:shadow-[0_8px_9px_-4px_rgba(59,113,202,0.3),0_4px_18px_0_rgba(59,113,202,0.2)]"
          data-te-ripple-init
          data-te-ripple-color="light">
          Understood
        </button>
      </div>
    </div>
  </div>
</div>
 
 

     

     
                    <button
                        data-modal-toggle="successModal" 
                        className="flex items-center justify-content-center justify-between w-80 px-6 py-3 text-sm tracking-wide text-white capitalize transition-colors duration-300 transform bg-blue-500 rounded-md hover:bg-blue-400 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-50 ">
                        <span>S&apos;incrire </span>

                        <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 rtl:-scale-x-100" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd"
                                d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                                clip-rule="evenodd" />
                        </svg>
                    </button>
                </form>
            </div>
        </div>
    </div>
</section>
 
    </>
  )
}
